#!/bin/sh
set -e
package_name=system-config-printer-jobs
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/etc/xdg/autostart/print-applet.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/system-config-printer.desktop"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/etc/xdg/autostart/print-applet.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/system-config-printer.desktop"
;;
esac
exit 0
